version: '3.0'
services:
    db:
        container_name: database_repostory
        image: mysql
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
        expose:
            -   "3306"
        volumes:
            - /volumes/repostory:/var/lib/mysql

    app:
        container_name: backend_repostory
        build: .
        image: repostory3-app
        environment:
            - PORT=$PORT
            - CLIENT_SECRET=$CLIENT_SECRET
            - CLIENT_ID=$CLIENT_ID
            - SECRET=$SECRET
            - EXPIRES_IN=$EXPIRES_IN
            - REFRESH_TOKEN_EXPIRES_IN=$REFRESH_TOKEN_EXPIRES_IN
            - DATABASE_URL=$DATABASE_URL
            - WAIT_HOSTS=db:3306
        ports:
            - "3000:3000"
        depends_on:
            - db
